add_newline = true
command_timeout = 200

# Generated by Omarchy from ~/.config/omarchy/current/theme/colors.toml

format = "[$directory$git_branch$git_status]($style)$character"

[character]
error_symbol = "[✗](bold {{ color1 }})"
success_symbol = "[❯](bold {{ accent }})"

[directory]
truncation_length = 2
truncation_symbol = "…/"
repo_root_style = "bold {{ accent }}"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "
style = "{{ foreground }}"

[git_branch]
format = "[$branch]($style) "
style = "italic {{ accent }}"

[git_status]
format = '[$all_status$ahead_behind]($style)'
style = "{{ color8 }}"
ahead = "⇡${count} "
behind = "⇣${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
conflicted = "=${count} "
untracked = "?${count} "
modified = "!${count} "
staged = "+${count} "
renamed = "»${count} "
deleted = "✘${count} "
stashed = "*${count} "
